<a href="https://colab.research.google.com/github/bindupriyakokku-blip/Movie-recommender-mini-system2/blob/main/Movie_recommender_mini_system_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data = {
    "title": [
        # Telugu
        "RRR",
        "Baahubali The Beginning",
        "Baahubali The Conclusion",
        "Pushpa The Rise",
        "Arjun Reddy",
        "Jersey",
        "Eega",

        # Hindi
        "3 Idiots",
        "Dangal",
        "PK",
        "War",
        "Brahmastra",

        # Tamil
        "Vikram",
        "Kaithi",
        "Master",
        "Jailer",

        # Malayalam
        "Drishyam",
        "Lucifer",
        "Minnal Murali",

        # Kannada
        "KGF Chapter 1",
        "KGF Chapter 2",
        "Kantara",

        # English
        "Avengers Endgame",
        "Avengers Infinity War",
        "Iron Man",
        "Thor Ragnarok",
        "Black Panther",
        "Spider-Man Homecoming",
        "Doctor Strange",
        "Interstellar",
        "Inception",
        "The Dark Knight",
        "Avatar"
    ],

    "language": [
        "Telugu", "Telugu", "Telugu", "Telugu", "Telugu", "Telugu", "Telugu",
        "Hindi", "Hindi", "Hindi", "Hindi", "Hindi",
        "Tamil", "Tamil", "Tamil", "Tamil",
        "Malayalam", "Malayalam", "Malayalam",
        "Kannada", "Kannada", "Kannada",
        "English", "English", "English", "English", "English",
        "English", "English", "English", "English", "English", "English"
    ],

    "genre": [
        "Action Drama Historical",
        "Action Adventure Fantasy",
        "Action Adventure Fantasy",
        "Action Drama Thriller",
        "Romance Drama",
        "Sports Drama",
        "Fantasy Thriller",

        "Comedy Drama",
        "Sports Drama",
        "Comedy Fantasy Drama",
        "Action Thriller",
        "Fantasy Action Adventure",

        "Action Thriller Crime",
        "Action Crime Thriller",
        "Action Drama",
        "Action Thriller",

        "Crime Thriller Drama",
        "Action Political Thriller",
        "Superhero Fantasy Action",

        "Action Crime Drama",
        "Action Crime Drama",
        "Action Mystery Thriller",

        "Action Adventure Superhero",
        "Action Adventure Superhero",
        "Action Sci-Fi Superhero",
        "Action Adventure Fantasy",
        "Action Adventure Superhero",
        "Action Adventure Superhero",
        "Action Fantasy Sci-Fi",
        "Science Fiction Drama",
        "Science Fiction Thriller",
        "Action Crime Drama",
        "Science Fiction Adventure"
    ],

    "description": [
        "Two revolutionaries fight for freedom and friendship",
        "A warrior fights to protect his kingdom and family",
        "A king returns to reclaim his kingdom and defeat his enemies",
        "A courageous man rises to power in a dangerous world",
        "A young man experiences intense love and emotional struggles",
        "A talented cricketer fights to return to the sport and fulfill his dreams",
        "A man uses magical powers to fight enemies and protect his loved one",

        "Three engineering students learn about friendship life and education",
        "A father trains his daughters to become successful wrestlers",
        "An alien comes to Earth and questions religion and society",
        "Two soldiers fight against a dangerous enemy",
        "A young man discovers powerful supernatural weapons and fights evil",

        "A police officer investigates a dangerous criminal gang",
        "A prisoner helps a police officer solve a dangerous case",
        "A teacher faces a powerful criminal and fights for his students",
        "A powerful jailer protects his family and fights criminals",

        "A family tries to protect itself from a serious crime investigation",
        "A powerful man returns to Kerala and fights political enemies",
        "A young man discovers superpowers and becomes a superhero",

        "A man rises from poverty to become a powerful gangster",
        "A powerful gangster fights to control the gold mining empire",
        "A village man faces supernatural forces and protects his people",

        "Superheroes fight together to save the universe",
        "Avengers fight against a powerful villain to save the universe",
        "A billionaire builds a powerful armored suit and becomes a superhero",
        "Thor fights enemies and tries to save Asgard",
        "A superhero protects Wakanda from enemies",
        "A young superhero learns to become a better hero",
        "A doctor discovers magical powers and protects the world",
        "Astronauts travel through space to find a new home for humanity",
        "A thief enters dreams to perform a difficult mission",
        "A superhero fights a dangerous criminal in Gotham City",
        "Humans explore a new planet and discover a new world"
    ]
}

movies = pd.DataFrame(data)

print("Total Movies:", len(movies))
display(movies)

Total Movies: 33

,title,language,genre,description
0,RRR,Telugu,Action Drama Historical,Two revolutionaries fight for freedom and frie...
1,Baahubali The Beginning,Telugu,Action Adventure Fantasy,A warrior fights to protect his kingdom and fa...
2,Baahubali The Conclusion,Telugu,Action Adventure Fantasy,A king returns to reclaim his kingdom and defe...
3,Pushpa The Rise,Telugu,Action Drama Thriller,A courageous man rises to power in a dangerous...
4,Arjun Reddy,Telugu,Romance Drama,A young man experiences intense love and emoti...
5,Jersey,Telugu,Sports Drama,A talented cricketer fights to return to the s...
6,Eega,Telugu,Fantasy Thriller,A man uses magical powers to fight enemies and...
7,3 Idiots,Hindi,Comedy Drama,Three engineering students learn about friends...
8,Dangal,Hindi,Sports Drama,A father trains his daughters to become succes...
9,PK,Hindi,Comedy Fantasy Drama,An alien comes to Earth and questions religion...
10,War,Hindi,Action Thriller,Two soldiers fight against a dangerous enemy
11,Brahmastra,Hindi,Fantasy Action Adventure,A young man discovers powerful supernatural we...
12,Vikram,Tamil,Action Thriller Crime,A police officer investigates a dangerous crim...
13,Kaithi,Tamil,Action Crime Thriller,A prisoner helps a police officer solve a dang...
14,Master,Tamil,Action Drama,A teacher faces a powerful criminal and fights...
15,Jailer,Tamil,Action Thriller,A powerful jailer protects his family and figh...
16,Drishyam,Malayalam,Crime Thriller Drama,A family tries to protect itself from a seriou...
17,Lucifer,Malayalam,Action Political Thriller,A powerful man returns to Kerala and fights po...
18,Minnal Murali,Malayalam,Superhero Fantasy Action,A young man discovers superpowers and becomes ...
19,KGF Chapter 1,Kannada,Action Crime Drama,A man rises from poverty to become a powerful ...
20,KGF Chapter 2,Kannada,Action Crime Drama,A powerful gangster fights to control the gold...
21,Kantara,Kannada,Action Mystery Thriller,A village man faces supernatural forces and pr...
22,Avengers Endgame,English,Action Adventure Superhero,Superheroes fight together to save the universe
23,Avengers Infinity War,English,Action Adventure Superhero,Avengers fight against a powerful villain to s...
24,Iron Man,English,Action Sci-Fi Superhero,A billionaire builds a powerful armored suit a...
25,Thor Ragnarok,English,Action Adventure Fantasy,Thor fights enemies and tries to save Asgard
26,Black Panther,English,Action Adventure Superhero,A superhero protects Wakanda from enemies
27,Spider-Man Homecoming,English,Action Adventure Superhero,A young superhero learns to become a better hero
28,Doctor Strange,English,Action Fantasy Sci-Fi,A doctor discovers magical powers and protects...
29,Interstellar,English,Science Fiction Drama,Astronauts travel through space to find a new ...
30,Inception,English,Science Fiction Thriller,A thief enters dreams to perform a difficult m...
31,The Dark Knight,English,Action Crime Drama,A superhero fights a dangerous criminal in Got...
32,Avatar,English,Science Fiction Adventure,Humans explore a new planet and discover a new...

In [3]:
movies["features"] = (
    movies["genre"] + " " +
    movies["description"]
)

movies[["title", "language", "genre", "features"]]

,title,language,genre,features
0,RRR,Telugu,Action Drama Historical,Action Drama Historical Two revolutionaries fi...
1,Baahubali The Beginning,Telugu,Action Adventure Fantasy,Action Adventure Fantasy A warrior fights to p...
2,Baahubali The Conclusion,Telugu,Action Adventure Fantasy,Action Adventure Fantasy A king returns to rec...
3,Pushpa The Rise,Telugu,Action Drama Thriller,Action Drama Thriller A courageous man rises t...
4,Arjun Reddy,Telugu,Romance Drama,Romance Drama A young man experiences intense ...
5,Jersey,Telugu,Sports Drama,Sports Drama A talented cricketer fights to re...
6,Eega,Telugu,Fantasy Thriller,Fantasy Thriller A man uses magical powers to ...
7,3 Idiots,Hindi,Comedy Drama,Comedy Drama Three engineering students learn ...
8,Dangal,Hindi,Sports Drama,Sports Drama A father trains his daughters to ...
9,PK,Hindi,Comedy Fantasy Drama,Comedy Fantasy Drama An alien comes to Earth a...
10,War,Hindi,Action Thriller,Action Thriller Two soldiers fight against a d...
11,Brahmastra,Hindi,Fantasy Action Adventure,Fantasy Action Adventure A young man discovers...
12,Vikram,Tamil,Action Thriller Crime,Action Thriller Crime A police officer investi...
13,Kaithi,Tamil,Action Crime Thriller,Action Crime Thriller A prisoner helps a polic...
14,Master,Tamil,Action Drama,Action Drama A teacher faces a powerful crimin...
15,Jailer,Tamil,Action Thriller,Action Thriller A powerful jailer protects his...
16,Drishyam,Malayalam,Crime Thriller Drama,Crime Thriller Drama A family tries to protect...
17,Lucifer,Malayalam,Action Political Thriller,Action Political Thriller A powerful man retur...
18,Minnal Murali,Malayalam,Superhero Fantasy Action,Superhero Fantasy Action A young man discovers...
19,KGF Chapter 1,Kannada,Action Crime Drama,Action Crime Drama A man rises from poverty to...
20,KGF Chapter 2,Kannada,Action Crime Drama,Action Crime Drama A powerful gangster fights ...
21,Kantara,Kannada,Action Mystery Thriller,Action Mystery Thriller A village man faces su...
22,Avengers Endgame,English,Action Adventure Superhero,Action Adventure Superhero Superheroes fight t...
23,Avengers Infinity War,English,Action Adventure Superhero,Action Adventure Superhero Avengers fight agai...
24,Iron Man,English,Action Sci-Fi Superhero,Action Sci-Fi Superhero A billionaire builds a...
25,Thor Ragnarok,English,Action Adventure Fantasy,Action Adventure Fantasy Thor fights enemies a...
26,Black Panther,English,Action Adventure Superhero,Action Adventure Superhero A superhero protect...
27,Spider-Man Homecoming,English,Action Adventure Superhero,Action Adventure Superhero A young superhero l...
28,Doctor Strange,English,Action Fantasy Sci-Fi,Action Fantasy Sci-Fi A doctor discovers magic...
29,Interstellar,English,Science Fiction Drama,Science Fiction Drama Astronauts travel throug...
30,Inception,English,Science Fiction Thriller,Science Fiction Thriller A thief enters dreams...
31,The Dark Knight,English,Action Crime Drama,Action Crime Drama A superhero fights a danger...
32,Avatar,English,Science Fiction Adventure,Science Fiction Adventure Humans explore a new...

In [4]:
vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2)
)

feature_matrix = vectorizer.fit_transform(movies["features"])

print("Feature Matrix Shape:", feature_matrix.shape)

Feature Matrix Shape: (33, 354)

In [5]:
similarity_matrix = cosine_similarity(feature_matrix)

print("Similarity Matrix Created Successfully!")

Similarity Matrix Created Successfully!

In [6]:
def recommend_movies(movie_name, number_of_recommendations=5):

    movie_name = movie_name.strip().lower()

    # Exact title search
    matching_movies = movies[
        movies["title"].str.lower() == movie_name
    ]

    # If exact match is not found
    if matching_movies.empty:

        # Partial title search
        matching_movies = movies[
            movies["title"].str.lower().str.contains(movie_name, na=False)
        ]

    if matching_movies.empty:
        print("❌ Movie not found in our dataset.")
        print("\nAvailable movies are:")

        for title in movies["title"]:
            print("•", title)

        return

    movie_index = matching_movies.index[0]

    selected_movie = movies.iloc[movie_index]

    similarity_scores = list(
        enumerate(similarity_matrix[movie_index])
    )

    # Sort from highest similarity to lowest
    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    # Remove selected movie
    similarity_scores = [
        item for item in similarity_scores
        if item[0] != movie_index
    ]

    recommended_movies = similarity_scores[
        :number_of_recommendations
    ]

    print("\n" + "=" * 60)
    print("🎬 MOVIE RECOMMENDATION SYSTEM")
    print("=" * 60)

    print(f"\nSelected Movie : {selected_movie['title']}")
    print(f"Language       : {selected_movie['language']}")
    print(f"Genre          : {selected_movie['genre']}")

    print("\n⭐ Recommended Movies:\n")

    for rank, (index, score) in enumerate(
        recommended_movies, start=1
    ):

        movie = movies.iloc[index]

        print(
            f"{rank}. {movie['title']} "
            f"({movie['language']})"
        )

        print(f"   Genre      : {movie['genre']}")
        print(f"   Similarity : {score * 100:.2f}%")
        print()

In [7]:
recommend_movies("RRR")

============================================================
🎬 MOVIE RECOMMENDATION SYSTEM
============================================================

Selected Movie : RRR
Language       : Telugu
Genre          : Action Drama Historical

⭐ Recommended Movies:

1. Master (Tamil)
   Genre      : Action Drama
   Similarity : 9.72%

2. Pushpa The Rise (Telugu)
   Genre      : Action Drama Thriller
   Similarity : 9.12%

3. 3 Idiots (Hindi)
   Genre      : Comedy Drama
   Similarity : 8.77%

4. War (Hindi)
   Genre      : Action Thriller
   Similarity : 6.90%

5. Avengers Endgame (English)
   Genre      : Action Adventure Superhero
   Similarity : 6.71%

In [8]:
recommend_movies("3 Idiots")

============================================================
🎬 MOVIE RECOMMENDATION SYSTEM
============================================================

Selected Movie : 3 Idiots
Language       : Hindi
Genre          : Comedy Drama

⭐ Recommended Movies:

1. RRR (Telugu)
   Genre      : Action Drama Historical
   Similarity : 8.77%

2. Master (Tamil)
   Genre      : Action Drama
   Similarity : 8.50%

3. PK (Hindi)
   Genre      : Comedy Fantasy Drama
   Similarity : 7.19%

4. KGF Chapter 1 (Kannada)
   Genre      : Action Crime Drama
   Similarity : 2.07%

5. The Dark Knight (English)
   Genre      : Action Crime Drama
   Similarity : 1.91%

In [9]:
recommend_movies("Vikram")

============================================================
🎬 MOVIE RECOMMENDATION SYSTEM
============================================================

Selected Movie : Vikram
Language       : Tamil
Genre          : Action Thriller Crime

⭐ Recommended Movies:

1. Kaithi (Tamil)
   Genre      : Action Crime Thriller
   Similarity : 27.08%

2. The Dark Knight (English)
   Genre      : Action Crime Drama
   Similarity : 20.70%

3. War (Hindi)
   Genre      : Action Thriller
   Similarity : 15.73%

4. Drishyam (Malayalam)
   Genre      : Crime Thriller Drama
   Similarity : 9.63%

5. Jailer (Tamil)
   Genre      : Action Thriller
   Similarity : 9.31%

In [10]:
recommend_movies("Drishyam")

============================================================
🎬 MOVIE RECOMMENDATION SYSTEM
============================================================

Selected Movie : Drishyam
Language       : Malayalam
Genre          : Crime Thriller Drama

⭐ Recommended Movies:

1. Kaithi (Tamil)
   Genre      : Action Crime Thriller
   Similarity : 14.74%

2. Baahubali The Beginning (Telugu)
   Genre      : Action Adventure Fantasy
   Similarity : 11.89%

3. KGF Chapter 1 (Kannada)
   Genre      : Action Crime Drama
   Similarity : 10.35%

4. Vikram (Tamil)
   Genre      : Action Thriller Crime
   Similarity : 9.63%

5. The Dark Knight (English)
   Genre      : Action Crime Drama
   Similarity : 9.54%

In [11]:
recommend_movies("KGF Chapter 1")

============================================================
🎬 MOVIE RECOMMENDATION SYSTEM
============================================================

Selected Movie : KGF Chapter 1
Language       : Kannada
Genre          : Action Crime Drama

⭐ Recommended Movies:

1. KGF Chapter 2 (Kannada)
   Genre      : Action Crime Drama
   Similarity : 33.67%

2. Pushpa The Rise (Telugu)
   Genre      : Action Drama Thriller
   Similarity : 20.88%

3. The Dark Knight (English)
   Genre      : Action Crime Drama
   Similarity : 19.05%

4. Drishyam (Malayalam)
   Genre      : Crime Thriller Drama
   Similarity : 10.35%

5. Kaithi (Tamil)
   Genre      : Action Crime Thriller
   Similarity : 9.38%

In [12]:
recommend_movies("Avengers Endgame")

============================================================
🎬 MOVIE RECOMMENDATION SYSTEM
============================================================

Selected Movie : Avengers Endgame
Language       : English
Genre          : Action Adventure Superhero

⭐ Recommended Movies:

1. Avengers Infinity War (English)
   Genre      : Action Adventure Superhero
   Similarity : 45.31%

2. Black Panther (English)
   Genre      : Action Adventure Superhero
   Similarity : 25.10%

3. Spider-Man Homecoming (English)
   Genre      : Action Adventure Superhero
   Similarity : 22.25%

4. Thor Ragnarok (English)
   Genre      : Action Adventure Fantasy
   Similarity : 14.66%

5. Minnal Murali (Malayalam)
   Genre      : Superhero Fantasy Action
   Similarity : 9.65%

In [ ]:
movie_name = input("🎬 Enter movie name: ")

recommend_movies(movie_name, 5)